"""weread-mcp 网关协议与工厂。

`FakeWereadMcpClient` 既是离线测试替身，也是 `AI_WEREAD_MCP_FAKE=1` 时生产路径的替身，
因此 ai-service 在 weread-mcp 未启动时也能完整跑通全链路。
"""

from __future__ import annotations

from typing import Any, Protocol

from app.books.fake import FakeWereadMcpClient
from app.books.mcp_client import WereadMcpClient
from app.config import Settings


class WereadMcpGateway(Protocol):
    async def login_status(self) -> dict[str, Any]: ...
    async def login_qrcode(self) -> dict[str, Any]: ...
    async def set_api_key(self, api_key: str) -> dict[str, Any]: ...
    async def logout(self) -> dict[str, Any]: ...
    async def get_bookshelf(self) -> dict[str, Any]: ...
    async def search_books(self, keyword: str, count: int) -> dict[str, Any]: ...
    async def book_info(self, book_id: str) -> dict[str, Any]: ...
    async def book_progress(self, book_id: str) -> dict[str, Any]: ...
    async def readdata_detail(self, mode: str) -> dict[str, Any]: ...
    async def recommend_books(self, count: int) -> dict[str, Any]: ...
    async def similar_books(self, book_id: str, count: int) -> dict[str, Any]: ...


def create_weread_gateway(settings: Settings) -> WereadMcpGateway:
    """按配置创建真实 MCP 客户端或离线替身。"""
    if settings.weread_mcp_fake or not settings.weread_mcp_enabled or not settings.weread_mcp_url.strip():
        return FakeWereadMcpClient()
    return WereadMcpClient(settings)
