package com.adaptivelearning.knowledgebase.api;
import com.adaptivelearning.knowledgebase.application.*;import com.adaptivelearning.knowledgebase.domain.*;import com.adaptivelearning.shared.api.ApiResponse;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import lombok.RequiredArgsConstructor;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;import java.io.IOException;import java.util.*;
@RestController @RequestMapping("/api/v1") @RequiredArgsConstructor public class KnowledgeController {
 private final KnowledgeDocumentService docs;private final KnowledgeQaService qa;private final KnowledgeQaStreamService qaStream;
 public record SpaceRequest(@NotBlank@Size(max=120)String name,Long directionId,Integer version){}public record SearchRequest(@NotBlank@Size(max=2000)String query,@NotEmpty List<String>spaceIds,@Min(1)@Max(20)Integer topK){}public record SessionRequest(@Size(max=200)String title,@NotEmpty List<String>documentIds){}public record RenameRequest(@NotBlank@Size(max=200)String title){}public record MessageRequest(@NotBlank@Size(max=10000)String content){}public record DeleteRequest(@NotBlank String token){}public record FeedbackRequest(@Min(1)@Max(5)int rating,String reasonCode,@Size(max=1000)String comment){}public record CategoryRequest(String parentId,@NotBlank@Size(max=120)String name,Integer sortNo,Integer version){}public record DocumentCategoryRequest(String categoryId,@NotNull Integer version){}
 @GetMapping("/knowledge-spaces")public ApiResponse<List<KnowledgeSpaceEntity>>spaces(){return ApiResponse.ok(docs.spaces());}@PostMapping("/knowledge-spaces")@ResponseStatus(HttpStatus.CREATED)public ApiResponse<KnowledgeSpaceEntity>space(@Valid@RequestBody SpaceRequest r){return ApiResponse.ok(docs.createSpace(r.name(),r.directionId()));}@GetMapping("/knowledge-spaces/{id}")public ApiResponse<KnowledgeSpaceEntity>space(@PathVariable String id){return ApiResponse.ok(docs.space(id));}@PatchMapping("/knowledge-spaces/{id}")public ApiResponse<KnowledgeSpaceEntity>space(@PathVariable String id,@Valid@RequestBody SpaceRequest r){return ApiResponse.ok(docs.updateSpace(id,r.name(),r.directionId(),r.version()));}@DeleteMapping("/knowledge-spaces/{id}")@ResponseStatus(HttpStatus.ACCEPTED)public ApiResponse<Void>deleteSpace(@PathVariable String id){docs.deleteSpace(id);return ApiResponse.ok(null);}
 @GetMapping("/knowledge-spaces/{id}/documents")public ApiResponse<List<KnowledgeDocumentEntity>>documents(@PathVariable String id){return ApiResponse.ok(docs.documents(id));}@PostMapping(value="/knowledge-spaces/{id}/documents",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)@ResponseStatus(HttpStatus.ACCEPTED)public ApiResponse<KnowledgeDocumentEntity>upload(@PathVariable String id,@RequestPart("file")MultipartFile file){return ApiResponse.ok(docs.upload(id,file));}
 @GetMapping("/knowledge-spaces/{id}/categories")public ApiResponse<List<KnowledgeDocumentService.CategoryView>>categories(@PathVariable String id){return ApiResponse.ok(docs.categories(id));}
 @PostMapping("/knowledge-spaces/{id}/categories")@ResponseStatus(HttpStatus.CREATED)public ApiResponse<KnowledgeDocumentService.CategoryView>createCategory(@PathVariable String id,@Valid@RequestBody CategoryRequest r){return ApiResponse.ok(docs.createCategory(id,r.parentId(),r.name(),r.sortNo()));}
 @PatchMapping("/knowledge-spaces/{id}/categories/{categoryId}")public ApiResponse<KnowledgeDocumentService.CategoryView>updateCategory(@PathVariable String id,@PathVariable String categoryId,@Valid@RequestBody CategoryRequest r){return ApiResponse.ok(docs.updateCategory(id,categoryId,r.name(),r.sortNo(),r.version()));}
 @DeleteMapping("/knowledge-spaces/{id}/categories/{categoryId}")public ApiResponse<Void>deleteCategory(@PathVariable String id,@PathVariable String categoryId){docs.deleteCategory(id,categoryId);return ApiResponse.ok(null);}
 @PatchMapping("/documents/{id}/category")public ApiResponse<KnowledgeDocumentEntity>assignCategory(@PathVariable String id,@Valid@RequestBody DocumentCategoryRequest r){return ApiResponse.ok(docs.assignCategory(id,r.categoryId(),r.version()));}
 @GetMapping("/documents/{id}")public ApiResponse<KnowledgeDocumentService.DocumentDetail>document(@PathVariable String id){return ApiResponse.ok(docs.detail(id));}@GetMapping("/documents/{id}/content")public ApiResponse<List<KnowledgeDocumentService.ChunkView>>content(@PathVariable String id){return ApiResponse.ok(docs.documentContent(id));}@PostMapping("/documents/{id}/retry-jobs")public ApiResponse<KnowledgeDocumentEntity>retry(@PathVariable String id){return ApiResponse.ok(docs.retry(id));}@PostMapping(value="/documents/{id}/replacement",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)public ApiResponse<KnowledgeDocumentEntity>replace(@PathVariable String id,@RequestPart("file")MultipartFile file){return ApiResponse.ok(docs.replace(id,file));}@PostMapping("/documents/{id}/deletion-requests")public ApiResponse<KnowledgeDocumentService.DeleteToken>deleteRequest(@PathVariable String id){return ApiResponse.ok(docs.deletionRequest(id));}@PostMapping("/documents/{id}/deletion")@ResponseStatus(HttpStatus.ACCEPTED)public ApiResponse<Void>delete(@PathVariable String id,@Valid@RequestBody DeleteRequest r){docs.delete(id,r.token());return ApiResponse.ok(null);}
 @PostMapping("/knowledge-searches")public ApiResponse<KnowledgeQaService.SearchResult>search(@Valid@RequestBody SearchRequest r){return ApiResponse.ok(qa.search(r.query(),r.spaceIds(),r.topK()));}
 @GetMapping("/qa-sessions")public ApiResponse<List<QaSessionEntity>>sessions(){return ApiResponse.ok(qa.sessions());}@PostMapping("/qa-sessions")@ResponseStatus(HttpStatus.CREATED)public ApiResponse<QaSessionEntity>session(@Valid@RequestBody SessionRequest r){return ApiResponse.ok(qa.createSession(r.title(),r.documentIds()));}@PatchMapping("/qa-sessions/{id}")public ApiResponse<QaSessionEntity>renameSession(@PathVariable String id,@Valid@RequestBody RenameRequest r){return ApiResponse.ok(qa.renameSession(id,r.title()));}@DeleteMapping("/qa-sessions/{id}")public ApiResponse<Void>deleteSession(@PathVariable String id){qa.deleteSession(id);return ApiResponse.ok(null);}@GetMapping("/qa-sessions/{id}/messages")public ApiResponse<List<KnowledgeQaService.MessageView>>messages(@PathVariable String id){return ApiResponse.ok(qa.messages(id));}
 @PostMapping(value="/qa-sessions/{id}/messages",produces=MediaType.APPLICATION_JSON_VALUE)public ApiResponse<KnowledgeQaService.AnswerResult>ask(@PathVariable String id,@Valid@RequestBody MessageRequest r){return ApiResponse.ok(qa.ask(id,r.content()));}
 @PostMapping(value="/qa-sessions/{id}/messages",produces=MediaType.TEXT_EVENT_STREAM_VALUE)public SseEmitter askStream(@PathVariable String id,@Valid@RequestBody MessageRequest r){return qaStream.stream(id,r.content());}
 @PutMapping("/qa-messages/{id}/feedback")public ApiResponse<Void>feedback(@PathVariable String id,@Valid@RequestBody FeedbackRequest r){qa.feedback(id,r.rating(),r.reasonCode(),r.comment());return ApiResponse.ok(null);}
}
