package com.adaptivelearning.support.api;
import com.adaptivelearning.evaluation.application.AssessmentService;import com.adaptivelearning.evaluation.domain.QuestionEntity;import com.adaptivelearning.shared.api.*;import com.adaptivelearning.support.application.AdminService;import com.adaptivelearning.support.domain.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import lombok.RequiredArgsConstructor;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/v1/admin") @RequiredArgsConstructor public class AdminController {
 private final AdminService service;public record StatusRequest(@NotBlank String status,@NotNull Integer version,@NotBlank@Size(max=1000)String reason){}public record DirectionRequest(Long id,Long parentId,@NotBlank String code,@NotBlank String name,@NotBlank String status,int sortNo,Integer version){}public record KnowledgeRequest(Long id,@NotNull Long directionId,Long parentId,@NotBlank String code,@NotBlank String name,@Min(1)int level,@DecimalMin("0.0001")double defaultWeight,@NotBlank String status,Integer version){}public record DependencyRequest(@NotNull Long predecessorId,@NotNull Long successorId){}public record QuestionRequest(@NotBlank String type,@NotBlank String stem,List<String>options,@NotNull Object answer,Map<String,Object>rubric,String analysis,@Min(1)@Max(5)int difficulty,@NotEmpty List<Long>knowledgePointIds){}public record ModelRequest(@NotBlank String provider,@NotBlank String providerName,@NotBlank String baseUrl,String secretRef,@NotBlank String purpose,@NotBlank String modelName,Map<String,Object>parameters,@Min(1)int timeoutSeconds,@Min(1)long dailyLimit){}public record PromptRequest(@NotBlank String code,@NotBlank String content,Object schema){}
 @GetMapping("/users")@PreAuthorize("hasAuthority('user:read')")public ApiResponse<PageResponse<UserEntity>>users(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int pageSize,@RequestParam(required=false)String status){return ApiResponse.ok(service.users(page,pageSize,status));}@PostMapping("/users/{id}/status")@PreAuthorize("hasAuthority('user:status:write')")public ApiResponse<Void>status(@PathVariable String id,@Valid@RequestBody StatusRequest r){service.userStatus(id,r.status(),r.version(),r.reason());return ApiResponse.ok(null);}
 @GetMapping("/learning-directions")public ApiResponse<List<Map<String,Object>>>directions(){return ApiResponse.ok(service.directions());}@PostMapping("/learning-directions")@PreAuthorize("hasAuthority('direction:write')")public ApiResponse<Map<String,Object>>direction(@Valid@RequestBody DirectionRequest r){return ApiResponse.ok(service.saveDirection(r.id(),r.parentId(),r.code(),r.name(),r.status(),r.sortNo(),r.version()));}
 @GetMapping("/knowledge-points")public ApiResponse<List<Map<String,Object>>>knowledge(){return ApiResponse.ok(service.knowledgePoints());}@PostMapping("/knowledge-points")@PreAuthorize("hasAuthority('knowledge-point:write')")public ApiResponse<Map<String,Object>>knowledge(@Valid@RequestBody KnowledgeRequest r){return ApiResponse.ok(service.saveKnowledge(r.id(),r.directionId(),r.parentId(),r.code(),r.name(),r.level(),r.defaultWeight(),r.status(),r.version()));}@PostMapping("/knowledge-dependencies")@PreAuthorize("hasAuthority('knowledge-point:write')")public ApiResponse<Void>dependency(@Valid@RequestBody DependencyRequest r){service.dependency(r.predecessorId(),r.successorId());return ApiResponse.ok(null);}
 @PostMapping("/questions")@PreAuthorize("hasAuthority('question:review')")public ApiResponse<QuestionEntity>question(@Valid@RequestBody QuestionRequest r){return ApiResponse.ok(service.publicQuestion(new AssessmentService.QuestionInput(r.type(),r.stem(),r.options(),r.answer(),r.rubric(),r.analysis(),r.difficulty(),r.knowledgePointIds(),"PUBLIC")));}
 @GetMapping("/model-configs")@PreAuthorize("hasAuthority('model:config:write')")public ApiResponse<List<Map<String,Object>>>models(){return ApiResponse.ok(service.modelConfigs());}@PostMapping("/model-configs")@PreAuthorize("hasAuthority('model:config:write')")public ApiResponse<Map<String,Object>>model(@Valid@RequestBody ModelRequest r){return ApiResponse.ok(service.saveModel(r.provider(),r.providerName(),r.baseUrl(),r.secretRef(),r.purpose(),r.modelName(),r.parameters(),r.timeoutSeconds(),r.dailyLimit()));}
 @GetMapping("/prompt-templates")@PreAuthorize("hasAuthority('prompt:write')")public ApiResponse<List<Map<String,Object>>>prompts(){return ApiResponse.ok(service.prompts());}@PostMapping("/prompt-templates")@PreAuthorize("hasAuthority('prompt:write')")public ApiResponse<Map<String,Object>>prompt(@Valid@RequestBody PromptRequest r){return ApiResponse.ok(service.savePrompt(r.code(),r.content(),r.schema()));}
 @GetMapping("/audit-logs")@PreAuthorize("hasAuthority('audit:read')")public ApiResponse<PageResponse<AuditLogEntity>>audits(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int pageSize){return ApiResponse.ok(service.auditLogs(page,pageSize));}@GetMapping("/jobs")@PreAuthorize("hasAuthority('monitor:read')")public ApiResponse<Map<String,Object>>jobs(){return ApiResponse.ok(service.jobs());}@GetMapping("/system-metrics")@PreAuthorize("hasAuthority('monitor:read')")public ApiResponse<Map<String,Object>>metrics(){return ApiResponse.ok(service.metrics());}
}
