package com.adaptivelearning.support.application;

import com.adaptivelearning.evaluation.application.AssessmentService;import com.adaptivelearning.evaluation.domain.QuestionEntity;import com.adaptivelearning.goalproject.domain.DependencyGraphPolicy;import com.adaptivelearning.shared.api.PageResponse;import com.adaptivelearning.shared.exception.*;import com.adaptivelearning.shared.security.SecurityUtils;import com.adaptivelearning.support.domain.*;import com.adaptivelearning.support.infrastructure.*;import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.baomidou.mybatisplus.core.toolkit.IdWorker;import com.fasterxml.jackson.core.*;import com.fasterxml.jackson.databind.ObjectMapper;import lombok.RequiredArgsConstructor;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import java.net.URI;import java.time.*;import java.util.*;
@Service @RequiredArgsConstructor public class AdminService {
 private final UserMapper users;private final AuditLogMapper audits;private final JdbcTemplate jdbc;private final ObjectMapper json;private final AuditService audit;private final AssessmentService assessment;
 public PageResponse<UserEntity>users(int page,int size,String status){var q=new LambdaQueryWrapper<UserEntity>().eq(status!=null,UserEntity::getStatus,status).orderByDesc(UserEntity::getCreatedAt);Page<UserEntity>p=users.selectPage(Page.of(page,Math.min(size,100)),q);p.getRecords().forEach(u->u.setPasswordHash("***"));return new PageResponse<>(p.getRecords(),p.getTotal(),page,Math.min(size,100));}
 public void userStatus(String publicId,String status,Integer version,String reason){if(!Set.of("ACTIVE","DISABLED","LOCKED").contains(status)||reason==null||reason.isBlank())bad("用户状态或原因不合法");UserEntity u=users.selectOne(new LambdaQueryWrapper<UserEntity>().eq(UserEntity::getPublicId,publicId));if(u==null)notFound();if(version==null||!version.equals(u.getVersion()))conflict();String before=u.getStatus();u.setStatus(status);if(users.updateById(u)!=1)conflict();audit.record("ADMIN_USER_STATUS","SYS_USER",publicId,before,status+":"+reason,"SUCCESS");}
 public List<Map<String,Object>>directions(){return jdbc.queryForList("SELECT id,parent_id,code,name,status,sort_no,version FROM learning_direction WHERE deleted_at IS NULL ORDER BY sort_no,id");}
 public Map<String,Object>saveDirection(Long id,Long parentId,String code,String name,String status,int sortNo,Integer version){if(code==null||!code.matches("[A-Z0-9_]{2,80}")||name==null||name.isBlank())bad("方向字段不合法");long entityId=id==null?IdWorker.getId():id;if(id==null)jdbc.update("INSERT INTO learning_direction(id,parent_id,code,name,status,sort_no,created_at,created_by,updated_at,updated_by,version) VALUES(?,?,?,?,?,?,?, ?,?,?,0)",entityId,parentId,code,name,status,sortNo,Instant.now(),SecurityUtils.currentUserId(),Instant.now(),SecurityUtils.currentUserId());else{int n=jdbc.update("UPDATE learning_direction SET parent_id=?,code=?,name=?,status=?,sort_no=?,updated_at=?,updated_by=?,version=version+1 WHERE id=? AND version=? AND deleted_at IS NULL",parentId,code,name,status,sortNo,Instant.now(),SecurityUtils.currentUserId(),id,version);if(n!=1)conflict();}return jdbc.queryForMap("SELECT id,parent_id,code,name,status,sort_no,version FROM learning_direction WHERE id=?",entityId);}
 public List<Map<String,Object>>knowledgePoints(){return jdbc.queryForList("SELECT id,direction_id,parent_id,code,name,level,default_weight,status,version FROM knowledge_point WHERE deleted_at IS NULL ORDER BY direction_id,level,id");}
 public Map<String,Object>saveKnowledge(Long id,long directionId,Long parentId,String code,String name,int level,double weight,String status,Integer version){if(code==null||name==null||name.isBlank()||level<1||weight<=0)bad("知识点字段不合法");long entityId=id==null?IdWorker.getId():id;if(id==null)jdbc.update("INSERT INTO knowledge_point(id,direction_id,parent_id,code,name,level,default_weight,status,created_at,created_by,updated_at,updated_by,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,0)",entityId,directionId,parentId,code,name,level,weight,status,Instant.now(),SecurityUtils.currentUserId(),Instant.now(),SecurityUtils.currentUserId());else if(jdbc.update("UPDATE knowledge_point SET direction_id=?,parent_id=?,code=?,name=?,level=?,default_weight=?,status=?,updated_at=?,updated_by=?,version=version+1 WHERE id=? AND version=?",directionId,parentId,code,name,level,weight,status,Instant.now(),SecurityUtils.currentUserId(),id,version)!=1)conflict();return jdbc.queryForMap("SELECT id,direction_id,parent_id,code,name,level,default_weight,status,version FROM knowledge_point WHERE id=?",entityId);}
 public void dependency(long predecessor,long successor){List<DependencyGraphPolicy.Edge>edges=jdbc.query("SELECT predecessor_id,successor_id FROM knowledge_dependency",(rs,row)->new DependencyGraphPolicy.Edge(rs.getLong(1),rs.getLong(2)));edges=new ArrayList<>(edges);edges.add(new DependencyGraphPolicy.Edge(predecessor,successor));DependencyGraphPolicy.requireAcyclic(edges);jdbc.update("INSERT INTO knowledge_dependency(predecessor_id,successor_id,type) VALUES(?,?,'PREREQUISITE')",predecessor,successor);}
 public QuestionEntity publicQuestion(AssessmentService.QuestionInput input){return assessment.createQuestion(input,true);}
 public List<Map<String,Object>>modelConfigs(){return jdbc.queryForList("SELECT mc.public_id,mc.purpose,mc.model_name,mc.parameters_json,mc.timeout_seconds,mc.daily_limit,mc.status,mc.version,mp.provider,mp.name provider_name,mp.base_url,CASE WHEN mp.encrypted_secret_ref IS NULL THEN NULL ELSE '********' END secret_mask FROM model_config mc JOIN model_provider_config mp ON mp.id=mc.provider_id WHERE mc.deleted_at IS NULL");}
 public Map<String,Object>saveModel(String provider,String providerName,String baseUrl,String secretRef,String purpose,String modelName,Map<String,Object>params,int timeout,long dailyLimit){try{URI u=URI.create(baseUrl);if(!Set.of("https","http").contains(u.getScheme()))throw new Exception();}catch(Exception e){bad("模型 Base URL 不合法");}long providerId=IdWorker.getId(),modelId=IdWorker.getId();jdbc.update("INSERT INTO model_provider_config(id,public_id,provider,name,encrypted_secret_ref,base_url,status,created_at,created_by,updated_at,updated_by,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,0)",providerId,UUID.randomUUID().toString(),provider,providerName,secretRef,baseUrl,"ACTIVE",Instant.now(),SecurityUtils.currentUserId(),Instant.now(),SecurityUtils.currentUserId());String publicId=UUID.randomUUID().toString();jdbc.update("INSERT INTO model_config(id,public_id,provider_id,purpose,model_name,parameters_json,timeout_seconds,daily_limit,status,created_at,created_by,updated_at,updated_by,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,0)",modelId,publicId,providerId,purpose,modelName,toJson(params),timeout,dailyLimit,"ACTIVE",Instant.now(),SecurityUtils.currentUserId(),Instant.now(),SecurityUtils.currentUserId());audit.record("MODEL_CONFIG_CREATE","MODEL_CONFIG",publicId,null,purpose+":"+modelName,"SUCCESS");return modelConfigs().stream().filter(x->publicId.equals(x.get("public_id"))).findFirst().orElse(Map.of());}
 public List<Map<String,Object>>prompts(){return jdbc.queryForList("SELECT public_id,code,version_no,status,created_at,created_by FROM prompt_template ORDER BY code,version_no DESC");}
 public Map<String,Object>savePrompt(String code,String content,Object schema){Integer next=jdbc.queryForObject("SELECT COALESCE(MAX(version_no),0)+1 FROM prompt_template WHERE code=?",Integer.class,code);String id=UUID.randomUUID().toString();jdbc.update("INSERT INTO prompt_template(id,public_id,code,version_no,content,schema_json,status,created_at,created_by) VALUES(?,?,?,?,?,?,?,?,?)",IdWorker.getId(),id,code,next,content,toJson(schema),"DRAFT",Instant.now(),SecurityUtils.currentUserId());return jdbc.queryForMap("SELECT public_id,code,version_no,status,created_at FROM prompt_template WHERE public_id=?",id);}
 public PageResponse<AuditLogEntity>auditLogs(int page,int size){Page<AuditLogEntity>p=audits.selectPage(Page.of(page,Math.min(size,100)),new LambdaQueryWrapper<AuditLogEntity>().orderByDesc(AuditLogEntity::getCreatedAt));return new PageResponse<>(p.getRecords(),p.getTotal(),page,Math.min(size,100));}
 public Map<String,Object>jobs(){return Map.of("planning",jdbc.queryForList("SELECT public_id,job_type,status,error_code,started_at,finished_at FROM planning_job ORDER BY created_at DESC LIMIT 100"),"documents",jdbc.queryForList("SELECT public_id,job_type,status,attempts,error_code,updated_at FROM document_job ORDER BY created_at DESC LIMIT 100"),"outboxPending",jdbc.queryForObject("SELECT COUNT(*) FROM outbox_event WHERE status='PENDING'",Long.class));}
 public Map<String,Object>metrics(){return Map.of("users",jdbc.queryForObject("SELECT COUNT(*) FROM sys_user WHERE deleted_at IS NULL",Long.class),"activeGoals",jdbc.queryForObject("SELECT COUNT(*) FROM learning_goal WHERE status='ACTIVE' AND deleted_at IS NULL",Long.class),"indexedDocuments",jdbc.queryForObject("SELECT COUNT(*) FROM knowledge_document WHERE status='INDEXED'",Long.class),"pendingJobs",jdbc.queryForObject("SELECT (SELECT COUNT(*) FROM planning_job WHERE status IN ('QUEUED','RUNNING'))+(SELECT COUNT(*) FROM document_job WHERE status='RUNNING')",Long.class),"generatedAt",Instant.now());}
 private String toJson(Object v){try{return json.writeValueAsString(v);}catch(JsonProcessingException e){throw new IllegalStateException(e);}}private void bad(String m){throw new BusinessException(ErrorCode.COMMON_VALIDATION_ERROR,m);}private void conflict(){throw new BusinessException(ErrorCode.RESOURCE_VERSION_CONFLICT,"资源版本冲突");}private void notFound(){throw new BusinessException(ErrorCode.RESOURCE_NOT_FOUND,"资源不存在");}
}
