package com.adaptivelearning.support.application;
import com.adaptivelearning.shared.api.PageResponse;import com.adaptivelearning.shared.exception.*;import com.adaptivelearning.shared.security.SecurityUtils;import com.adaptivelearning.support.domain.*;import com.adaptivelearning.support.infrastructure.NotificationMappers.*;import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.fasterxml.jackson.core.*;import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import lombok.RequiredArgsConstructor;import org.springframework.dao.DuplicateKeyException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import java.time.*;import java.util.*;
@Service @RequiredArgsConstructor public class NotificationService {
 private final NotificationMapper mapper;private final NotificationPreferenceMapper preferences;private final JdbcTemplate jdbc;private final ObjectMapper json;
 @org.springframework.beans.factory.annotation.Value("${app.scheduling.enabled:true}") private boolean schedulingEnabled;
 public record PreferenceView(Map<String,Boolean> values,int version){}
 public PageResponse<NotificationEntity>list(int page,int size,Boolean unread){var q=new LambdaQueryWrapper<NotificationEntity>().eq(NotificationEntity::getUserId,SecurityUtils.currentUserId()).isNull(Boolean.TRUE.equals(unread),NotificationEntity::getReadAt).orderByDesc(NotificationEntity::getCreatedAt);Page<NotificationEntity>p=mapper.selectPage(Page.of(page,Math.min(100,size)),q);return new PageResponse<>(p.getRecords(),p.getTotal(),page,Math.min(100,size));}
 public void read(String id){NotificationEntity n=mapper.selectOne(new LambdaQueryWrapper<NotificationEntity>().eq(NotificationEntity::getPublicId,id).eq(NotificationEntity::getUserId,SecurityUtils.currentUserId()));if(n==null)throw new BusinessException(ErrorCode.RESOURCE_NOT_FOUND,"通知不存在");if(n.getReadAt()==null){n.setReadAt(Instant.now());n.setStatus("READ");mapper.updateById(n);}}
 public PreferenceView preference(){NotificationPreferenceEntity p=preferences.selectOne(new LambdaQueryWrapper<NotificationPreferenceEntity>().eq(NotificationPreferenceEntity::getUserId,SecurityUtils.currentUserId()));Map<String,Boolean>defaults=Map.of("TASK_DUE",true,"TASK_OVERDUE",true,"REPORT",true,"DOCUMENT",true);return p==null?new PreferenceView(defaults,0):new PreferenceView(readPrefs(p.getPreferenceJson()),p.getVersion()==null?0:p.getVersion());}
 public PreferenceView savePreference(Map<String,Boolean>values,Integer version){NotificationPreferenceEntity p=preferences.selectOne(new LambdaQueryWrapper<NotificationPreferenceEntity>().eq(NotificationPreferenceEntity::getUserId,SecurityUtils.currentUserId()));if(p==null){p=new NotificationPreferenceEntity();p.setUserId(SecurityUtils.currentUserId());}else if(version==null||!version.equals(p.getVersion()))throw new BusinessException(ErrorCode.RESOURCE_VERSION_CONFLICT,"通知偏好已更新");p.setPreferenceJson(write(values));if(p.getId()==null)preferences.insert(p);else preferences.updateById(p);return new PreferenceView(values,p.getVersion()==null?0:p.getVersion());}
 public void create(long user,String type,String title,String content,String bizType,String bizId,String dedupe){if(!enabled(user,type)&&!type.startsWith("SECURITY"))return;NotificationEntity n=new NotificationEntity();n.setPublicId(UUID.randomUUID().toString());n.setUserId(user);n.setType(type);n.setChannel("IN_APP");n.setTitle(title);n.setContent(content);n.setBizType(bizType);n.setBizId(bizId);n.setStatus("SENT");n.setScheduledAt(Instant.now());n.setSentAt(Instant.now());n.setDedupeKey(dedupe);n.setCreatedAt(Instant.now());try{mapper.insert(n);}catch(DuplicateKeyException ignored){}}
 @Scheduled(fixedDelayString="PT5M")public void scanTasks(){if(!schedulingEnabled)return;List<Map<String,Object>>rows=jdbc.queryForList("SELECT t.user_id,t.public_id,t.title,t.due_at FROM learning_task t WHERE t.lifecycle_status NOT IN ('COMPLETED','CANCELED') AND t.deleted_at IS NULL AND t.due_at BETWEEN ? AND ?",Instant.now().minus(Duration.ofDays(1)),Instant.now().plus(Duration.ofMinutes(30)));for(var r:rows){Instant due=((java.sql.Timestamp)r.get("due_at")).toInstant();boolean overdue=due.isBefore(Instant.now());String id=(String)r.get("public_id");create(((Number)r.get("user_id")).longValue(),overdue?"TASK_OVERDUE":"TASK_DUE",overdue?"任务已逾期":"任务即将到期",String.valueOf(r.get("title")),"TASK",id,(overdue?"TASK_OVERDUE:":"TASK_DUE:")+id+":"+(overdue?LocalDate.now():due));}}
 @Scheduled(cron="0 30 3 * * *")public void cleanup(){if(!schedulingEnabled)return;jdbc.update("DELETE FROM refresh_token WHERE expires_at<?",Instant.now().minus(Duration.ofDays(7)));jdbc.update("DELETE FROM idempotency_record WHERE expires_at<?",Instant.now());jdbc.update("UPDATE plan_confirmation SET status='EXPIRED' WHERE status='PENDING' AND expires_at<?",Instant.now());}
 private boolean enabled(long user,String type){NotificationPreferenceEntity p=preferences.selectOne(new LambdaQueryWrapper<NotificationPreferenceEntity>().eq(NotificationPreferenceEntity::getUserId,user));if(p==null)return true;return readPrefs(p.getPreferenceJson()).getOrDefault(type,true);}
 private Map<String,Boolean>readPrefs(String v){try{return json.readValue(v,new TypeReference<>(){});}catch(Exception e){return Map.of();}}private String write(Object v){try{return json.writeValueAsString(v);}catch(JsonProcessingException e){throw new IllegalStateException(e);}}
}
