package com.adaptivelearning.execution.application;
import com.adaptivelearning.execution.domain.*;import com.adaptivelearning.execution.infrastructure.*;import com.adaptivelearning.execution.infrastructure.TutoringMappers.*;import com.adaptivelearning.knowledgebase.application.KnowledgeQaService;import com.adaptivelearning.shared.exception.*;import com.adaptivelearning.shared.security.SecurityUtils;import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.fasterxml.jackson.core.*;import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import java.time.Instant;import java.util.*;
@Service @RequiredArgsConstructor public class TutoringService {
 private final TutoringSessionMapper sessions;private final TutoringMessageMapper messages;private final LearningTaskMapper tasks;private final KnowledgeQaService qa;private final ObjectMapper json;
 public record SessionView(TutoringSessionEntity session,List<TutoringMessageEntity>messages){}
 public TutoringSessionEntity start(String taskId,String mode,List<String>spaces){LearningTaskEntity t=tasks.selectOne(new LambdaQueryWrapper<LearningTaskEntity>().eq(LearningTaskEntity::getPublicId,taskId).eq(LearningTaskEntity::getUserId,SecurityUtils.currentUserId()));if(t==null)notFound();if(!Set.of("SOCRATIC","STEP_BY_STEP","DIRECT").contains(mode))throw new BusinessException(ErrorCode.COMMON_VALIDATION_ERROR,"辅导模式不合法");if(spaces!=null)spaces.forEach(id->qa.search("授权检查",List.of(id),1));TutoringSessionEntity s=new TutoringSessionEntity();s.setPublicId(UUID.randomUUID().toString());s.setUserId(t.getUserId());s.setTaskId(t.getId());s.setMode(mode);s.setStatus("ACTIVE");s.setKnowledgeScopeJson(write(spaces==null?List.of():spaces));s.setStartedAt(Instant.now());sessions.insert(s);return s;}
 public TutoringMessageEntity ask(String sessionId,String question,boolean allowFinalAnswer){TutoringSessionEntity s=owned(sessionId);save(s,"USER",question,0);long prior=messages.selectCount(new LambdaQueryWrapper<TutoringMessageEntity>().eq(TutoringMessageEntity::getSessionId,s.getId()).eq(TutoringMessageEntity::getRole,"ASSISTANT"));int level=(int)Math.min(3,prior+1);List<String>spaces=read(s.getKnowledgeScopeJson());KnowledgeQaService.SearchResult result=spaces.isEmpty()?null:qa.search(question,spaces,3);String evidence=result==null||!result.evidenceSufficient()?"":result.hits().get(0).quotePreview()+" [S1]";String content;if("SOCRATIC".equals(s.getMode())&&level==1)content="先想一想：这个问题中你已经确定的条件是什么？你能把目标拆成一个更小的问题吗？";else if("SOCRATIC".equals(s.getMode())&&level==2)content="提示：尝试把相关概念的输入、处理和输出分别列出来。资料线索："+evidence;else if(!allowFinalAnswer)content="下一步提示：根据“"+evidence+"”写出你自己的结论，我可以继续检查。";else content=evidence.isBlank()?"当前授权资料证据不足。请描述你已尝试的步骤，或补充资料后继续。":"参考当前资料，关键依据是："+evidence+"。请结合任务验收标准完成实践，并核对引用上下文。";return save(s,"ASSISTANT",content,level);}
 public SessionView get(String id){TutoringSessionEntity s=owned(id);return new SessionView(s,messages.selectList(new LambdaQueryWrapper<TutoringMessageEntity>().eq(TutoringMessageEntity::getSessionId,s.getId()).orderByAsc(TutoringMessageEntity::getCreatedAt)));}
 private TutoringMessageEntity save(TutoringSessionEntity s,String role,String content,int level){if(content==null||content.isBlank()||content.length()>10000)throw new BusinessException(ErrorCode.COMMON_VALIDATION_ERROR,"辅导消息不合法");TutoringMessageEntity m=new TutoringMessageEntity();m.setPublicId(UUID.randomUUID().toString());m.setSessionId(s.getId());m.setRole(role);m.setContent(content);m.setGuidanceLevel(level);m.setCreatedAt(Instant.now());messages.insert(m);return m;}
 private TutoringSessionEntity owned(String id){TutoringSessionEntity s=sessions.selectOne(new LambdaQueryWrapper<TutoringSessionEntity>().eq(TutoringSessionEntity::getPublicId,id).eq(TutoringSessionEntity::getUserId,SecurityUtils.currentUserId()));if(s==null)notFound();return s;}private List<String>read(String v){try{return json.readValue(v,new TypeReference<>(){});}catch(Exception e){return List.of();}}private String write(Object v){try{return json.writeValueAsString(v);}catch(JsonProcessingException e){throw new IllegalStateException(e);}}private void notFound(){throw new BusinessException(ErrorCode.RESOURCE_NOT_FOUND,"资源不存在");}
}
