package com.adaptivelearning.knowledgebase.application;

import com.adaptivelearning.knowledgebase.domain.*;import com.adaptivelearning.knowledgebase.infrastructure.KnowledgeMappers.*;import com.adaptivelearning.shared.exception.*;import com.adaptivelearning.shared.security.SecurityUtils;import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.fasterxml.jackson.core.*;import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import lombok.RequiredArgsConstructor;import org.springframework.beans.factory.annotation.Value;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import java.math.*;import java.time.*;import java.util.*;
@Service @RequiredArgsConstructor public class KnowledgeQaService {
 private final KnowledgeDocumentService documents;private final SpaceMapper spaceMapper;private final QaSessionMapper sessionMapper;private final QaMessageMapper messageMapper;private final QaCitationMapper citationMapper;private final QaFeedbackMapper feedbackMapper;private final JdbcTemplate jdbc;private final ObjectMapper json;private final TextVectorizer vectorizer;@Value("${app.rag.top-k:5}")private int defaultTopK;
 public record SearchHit(String citationId,String documentId,String documentVersionId,long chunkId,String fileName,List<String>titlePath,Integer pageFrom,Integer pageTo,String quotePreview,double score){}
 public record SearchResult(boolean evidenceSufficient,List<SearchHit>hits,long latencyMs){}
 public record MessageView(QaMessageEntity message,List<QaCitationEntity>citations){}
 public record AnswerResult(MessageView userMessage,MessageView assistantMessage,boolean evidenceSufficient){}
 private record Candidate(long chunkId,long versionId,String documentId,String fileName,String text,String vectorJson,Integer pageFrom,Integer pageTo){}
 public SearchResult search(String query,List<String>spaceIds,Integer topK){long begin=System.nanoTime();if(query==null||query.isBlank())throw new BusinessException(ErrorCode.COMMON_VALIDATION_ERROR,"检索问题不能为空");if(spaceIds==null||spaceIds.isEmpty())throw new BusinessException(ErrorCode.COMMON_VALIDATION_ERROR,"至少选择一个知识空间");List<Long>ids=spaceIds.stream().map(documents::accessibleSpace).map(KnowledgeSpaceEntity::getId).toList();String marks=String.join(",",Collections.nCopies(ids.size(),"?"));List<Object>args=new ArrayList<>(ids);args.add(SecurityUtils.currentUserId());List<Candidate>candidates=jdbc.query("""
  SELECT c.id,c.document_version_id,d.public_id,d.display_name,c.text,c.vector_json,c.page_from,c.page_to
  FROM knowledge_chunk c JOIN document_version v ON v.id=c.document_version_id
  JOIN knowledge_document d ON d.id=v.document_id JOIN knowledge_space s ON s.id=d.space_id
  WHERE d.space_id IN ("""+marks+") AND d.status='INDEXED' AND v.version_no=d.active_version_no AND (s.visibility='PUBLIC' OR s.user_id=?)",
  (rs,row)->new Candidate(rs.getLong(1),rs.getLong(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),(Integer)rs.getObject(7),(Integer)rs.getObject(8)),args.toArray());double[]q=vectorizer.vector(query);
  record Scored(Candidate c,double score){}List<Scored>scored=candidates.stream().map(c->{double cosine=vectorizer.cosine(q,readVector(c.vectorJson())),keyword=vectorizer.keyword(query,c.text());return new Scored(c,0.7*Math.max(0,cosine)+0.3*keyword);}).sorted(Comparator.comparingDouble(Scored::score).reversed()).limit(Math.min(topK==null?defaultTopK:topK,20)).toList();boolean enough=!scored.isEmpty()&&scored.get(0).score()>=0.08;List<SearchHit>hits=new ArrayList<>();for(int i=0;i<scored.size();i++){Scored s=scored.get(i);Candidate c=s.c();hits.add(new SearchHit("S"+(i+1),c.documentId(),String.valueOf(c.versionId()),c.chunkId(),c.fileName(),List.of(),c.pageFrom(),c.pageTo(),preview(c.text()),s.score()));}return new SearchResult(enough,hits,(System.nanoTime()-begin)/1_000_000);}
 public QaSessionEntity createSession(String title,List<String>spaceIds){if(spaceIds==null||spaceIds.isEmpty())throw new BusinessException(ErrorCode.COMMON_VALIDATION_ERROR,"至少选择一个知识空间");spaceIds.forEach(documents::accessibleSpace);QaSessionEntity s=new QaSessionEntity();s.setPublicId(UUID.randomUUID().toString());s.setUserId(SecurityUtils.currentUserId());s.setTitle(title==null||title.isBlank()?"新对话":title);s.setSelectedSpaceJson(toJson(spaceIds));s.setStatus("ACTIVE");sessionMapper.insert(s);return s;}
 public List<QaSessionEntity>sessions(){return sessionMapper.selectList(new LambdaQueryWrapper<QaSessionEntity>().eq(QaSessionEntity::getUserId,SecurityUtils.currentUserId()).orderByDesc(QaSessionEntity::getUpdatedAt));}
 public AnswerResult ask(String sessionId,String question){long begin=System.nanoTime();QaSessionEntity s=ownedSession(sessionId);QaMessageEntity user=message(s,"USER",question,null,null,0);List<String>spaces=read(s.getSelectedSpaceJson(),new TypeReference<>(){});SearchResult result=search(question,spaces,defaultTopK);String content;String level;if(!result.evidenceSufficient()){content="当前选择的个人资料中没有足够证据回答这个问题。你可以补充资料、扩大已授权范围，或明确允许使用一般知识。";level="INSUFFICIENT";}else{StringBuilder b=new StringBuilder("根据当前已授权资料：\n\n");for(int i=0;i<Math.min(3,result.hits().size());i++){SearchHit h=result.hits().get(i);b.append(h.quotePreview()).append(" [").append(h.citationId()).append("]\n\n");}b.append("以上结论仅基于所列资料片段；请打开引用核对上下文。");content=b.toString();level="SUFFICIENT";}QaMessageEntity assistant=message(s,"ASSISTANT",content,"RAG",level,(System.nanoTime()-begin)/1_000_000);int rank=1;for(SearchHit h:result.hits()){QaCitationEntity c=new QaCitationEntity();c.setMessageId(assistant.getId());c.setCitationCode(h.citationId());c.setChunkId(h.chunkId());c.setDocumentVersionId(Long.parseLong(h.documentVersionId()));c.setQuotePreview(h.quotePreview());c.setRankNo(rank++);c.setScoreSnapshot(BigDecimal.valueOf(h.score()).setScale(6,RoundingMode.HALF_UP));c.setAccessStatus("AVAILABLE");citationMapper.insert(c);}return new AnswerResult(view(user),view(assistant),result.evidenceSufficient());}
 public List<MessageView>messages(String sessionId){QaSessionEntity s=ownedSession(sessionId);return messageMapper.selectList(new LambdaQueryWrapper<QaMessageEntity>().eq(QaMessageEntity::getSessionId,s.getId()).orderByAsc(QaMessageEntity::getCreatedAt)).stream().map(this::view).toList();}
 public void feedback(String messageId,int rating,String reason,String comment){if(rating<1||rating>5)throw new BusinessException(ErrorCode.COMMON_VALIDATION_ERROR,"反馈评分必须为 1～5");QaMessageEntity m=messageMapper.selectOne(new LambdaQueryWrapper<QaMessageEntity>().eq(QaMessageEntity::getPublicId,messageId));if(m==null)notFound();QaSessionEntity s=sessionMapper.selectById(m.getSessionId());if(s==null||!s.getUserId().equals(SecurityUtils.currentUserId()))notFound();QaFeedbackEntity f=feedbackMapper.selectOne(new LambdaQueryWrapper<QaFeedbackEntity>().eq(QaFeedbackEntity::getMessageId,m.getId()).eq(QaFeedbackEntity::getUserId,s.getUserId()));if(f==null){f=new QaFeedbackEntity();f.setMessageId(m.getId());f.setUserId(s.getUserId());f.setCreatedAt(Instant.now());}f.setRating(rating);f.setReasonCode(reason);f.setComment(comment);if(f.getId()==null)feedbackMapper.insert(f);else feedbackMapper.updateById(f);}
 private QaMessageEntity message(QaSessionEntity s,String role,String content,String mode,String evidence,long latency){if(content==null||content.isBlank()||content.length()>10000)throw new BusinessException(ErrorCode.COMMON_VALIDATION_ERROR,"消息不能为空且不能超过 10000 字");QaMessageEntity m=new QaMessageEntity();m.setPublicId(UUID.randomUUID().toString());m.setSessionId(s.getId());m.setRole(role);m.setContent(content);m.setAnswerMode(mode);m.setEvidenceLevel(evidence);m.setLatencyMs(latency);m.setCreatedAt(Instant.now());messageMapper.insert(m);return m;}
 private MessageView view(QaMessageEntity m){return new MessageView(m,citationMapper.selectList(new LambdaQueryWrapper<QaCitationEntity>().eq(QaCitationEntity::getMessageId,m.getId()).orderByAsc(QaCitationEntity::getRankNo)));}
 private QaSessionEntity ownedSession(String id){QaSessionEntity s=sessionMapper.selectOne(new LambdaQueryWrapper<QaSessionEntity>().eq(QaSessionEntity::getPublicId,id).eq(QaSessionEntity::getUserId,SecurityUtils.currentUserId()));if(s==null)notFound();return s;}
 private double[]readVector(String v){try{return json.readValue(v,double[].class);}catch(Exception e){return new double[128];}}private String preview(String t){String v=t.replaceAll("\\s+"," ").trim();return v.substring(0,Math.min(300,v.length()));}
 private <T>T read(String v,TypeReference<T>t){try{return json.readValue(v,t);}catch(Exception e){throw new IllegalStateException(e);}}private String toJson(Object v){try{return json.writeValueAsString(v);}catch(JsonProcessingException e){throw new IllegalStateException(e);}}private void notFound(){throw new BusinessException(ErrorCode.RESOURCE_NOT_FOUND,"资源不存在");}
}
