package com.adaptivelearning.shared.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    COMMON_VALIDATION_ERROR(HttpStatus.BAD_REQUEST),
    AUTH_UNAUTHENTICATED(HttpStatus.UNAUTHORIZED),
    AUTH_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED),
    AUTH_INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    AUTH_ACCOUNT_LOCKED(HttpStatus.LOCKED),
    AUTH_VERIFICATION_CODE_INVALID(HttpStatus.BAD_REQUEST),
    AUTH_FORBIDDEN(HttpStatus.FORBIDDEN),
    RESOURCE_ACCESS_DENIED(HttpStatus.FORBIDDEN),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    RESOURCE_VERSION_CONFLICT(HttpStatus.CONFLICT),
    STATE_TRANSITION_INVALID(HttpStatus.CONFLICT),
    IDEMPOTENCY_KEY_REUSED(HttpStatus.CONFLICT),
    DEPENDENCY_CYCLE_DETECTED(HttpStatus.CONFLICT),
    PLAN_CAPACITY_EXCEEDED(HttpStatus.UNPROCESSABLE_ENTITY),
    PLAN_CONFIRMATION_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    PLAN_CONTEXT_STALE(HttpStatus.UNPROCESSABLE_ENTITY),
    ASSESSMENT_ALREADY_SUBMITTED(HttpStatus.UNPROCESSABLE_ENTITY),
    FILE_SIZE_EXCEEDED(HttpStatus.PAYLOAD_TOO_LARGE),
    FILE_TYPE_UNSUPPORTED(HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    DOCUMENT_NO_EXTRACTABLE_TEXT(HttpStatus.UNPROCESSABLE_ENTITY),
    RAG_EVIDENCE_INSUFFICIENT(HttpStatus.UNPROCESSABLE_ENTITY),
    RATE_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS),
    MODEL_QUOTA_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS),
    MODEL_PROVIDER_ERROR(HttpStatus.BAD_GATEWAY),
    SERVICE_TEMPORARILY_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    MODEL_REQUEST_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus status() {
        return status;
    }
}
