<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import dayjs from 'dayjs'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { BarChart, LineChart } from 'echarts/charts'
import { GridComponent, TooltipComponent, LegendComponent } from 'echarts/components'
import VChart from 'vue-echarts'
import { api } from '../api/http'
use([CanvasRenderer,BarChart,LineChart,GridComponent,TooltipComponent,LegendComponent])
const range=ref<[string,string]>([dayjs().subtract(29,'day').format('YYYY-MM-DD'),dayjs().format('YYYY-MM-DD')]),overview=ref<any>({metrics:{},studyTime:[],mastery:[]}),reports=ref<any[]>([]),loading=ref(false)
const m=computed(()=>overview.value.metrics||{});const chart=computed(()=>({tooltip:{trigger:'axis'},grid:{left:42,right:18,top:25,bottom:35},xAxis:{type:'category',data:overview.value.studyTime.map((x:any)=>dayjs(x.date).format('M/D')),axisLine:{lineStyle:{color:'#d8ddd7'}}},yAxis:{type:'value',axisLabel:{formatter:(v:number)=>`${Math.round(v/60)}m`},splitLine:{lineStyle:{color:'#e8eae5'}}},series:[{name:'自动记录',type:'bar',stack:'time',data:overview.value.studyTime.map((x:any)=>x.autoSeconds),itemStyle:{color:'#1f6b4f',borderRadius:[3,3,0,0]}},{name:'手工补录',type:'bar',stack:'time',data:overview.value.studyTime.map((x:any)=>x.manualSeconds),itemStyle:{color:'#d39a3c'}}]}))
async function load(){loading.value=true;try{[overview.value,reports.value]=await Promise.all([api<any>({url:'/analytics/overview',params:{start:range.value[0],end:range.value[1]}}),api<any[]>({url:'/reports'})])}finally{loading.value=false}}
onMounted(load)
async function report(){await api({method:'POST',url:'/reports/generation-jobs',data:{type:'CUSTOM',periodStart:range.value[0],periodEnd:range.value[1]}});await load()}
</script>
<template><div v-loading="loading"><div class="page-head"><div><h2>让进步可见，也让不确定性可见</h2><p>所有指标包含分子、分母、时区、刷新时间和算法版本；无分母时显示“不适用”。</p></div><div class="toolbar"><el-date-picker v-model="range" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始" end-placeholder="结束" @change="load"/><el-button type="primary" @click="report">生成报告</el-button></div></div><div class="grid grid-4"><div class="panel stat"><span class="label">有效学习时长</span><div class="value">{{Math.round(Number(m.effectiveStudySeconds?.value||0)/3600*10)/10}}<small> 小时</small></div></div><div class="panel stat"><span class="label">任务完成率</span><div class="value">{{m.taskCompletionRate?.value??'—'}}<small v-if="m.taskCompletionRate?.value">%</small></div><span v-if="m.taskCompletionRate?.value==null" class="muted">期间无计划任务</span></div><div class="panel stat"><span class="label">按时完成率</span><div class="value">{{m.onTimeCompletionRate?.value??'—'}}<small v-if="m.onTimeCompletionRate?.value">%</small></div></div><div class="panel stat"><span class="label">逾期率</span><div class="value">{{m.overdueRate?.value??'—'}}<small v-if="m.overdueRate?.value">%</small></div></div></div><div class="grid analytics-grid"><section class="panel"><div class="panel-title"><div><h3>每日学习时长</h3><p>自动计时与手工补录分别展示，避免数据口径混淆。</p></div></div><v-chart class="chart" :option="chart" autoresize/></section><section class="panel"><div class="panel-title"><div><h3>掌握度快照</h3><p>分数不等同于置信度</p></div></div><div v-if="!overview.mastery.length" class="empty">暂无掌握度数据</div><div v-for="x in overview.mastery.slice(0,8)" :key="x.knowledgePointId" class="mastery-row"><div><b>{{x.name}}</b><small>{{x.evidenceCount}} 条证据 · 置信度 {{Math.round(Number(x.confidence)*100)}}%</small></div><el-progress :percentage="Math.round(Number(x.score)*100)"/></div></section></div><section class="panel reports"><div class="panel-title"><div><h3>学习报告</h3><p>同一周期重新生成会保留修订号</p></div></div><el-table :data="reports"><el-table-column prop="type" label="类型"/><el-table-column label="周期"><template #default="{row}">{{row.periodStart}} — {{row.periodEnd}}</template></el-table-column><el-table-column prop="revisionNo" label="修订"/><el-table-column prop="status" label="状态"/><el-table-column prop="createdAt" label="生成时间"/></el-table></section></div></template>
<style scoped>.analytics-grid{grid-template-columns:1.5fr 1fr;margin-top:18px}.chart{height:330px}.mastery-row{border-top:1px solid var(--line);padding:12px 0}.mastery-row b,.mastery-row small{display:block}.mastery-row small{font-size:10px;color:var(--muted);margin:4px 0}.reports{margin-top:18px}@media(max-width:900px){.analytics-grid{grid-template-columns:1fr}}</style>
