<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import dayjs from 'dayjs'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api/http'
const tab=ref('goals'), goals=ref<any[]>([]), projects=ref<any[]>([]), directions=ref<any[]>([]), dialog=ref(false), kind=ref<'goal'|'project'>('goal'), loading=ref(false)
const form=reactive<any>({directionId:undefined,name:'',type:'SKILL',description:'',priority:'MEDIUM',startDate:dayjs().format('YYYY-MM-DD'),dueDate:dayjs().add(60,'day').format('YYYY-MM-DD'),weeklyBudgetMinutes:420,repositoryUrl:''})
async function load(){const [g,p,d]=await Promise.all([api<any>({url:'/goals',params:{pageSize:100}}),api<any>({url:'/projects',params:{pageSize:100}}),api<any[]>({url:'/learning-directions'})]);goals.value=g.items;projects.value=p.items;directions.value=d}
onMounted(load)
function create(k:'goal'|'project'){kind.value=k;Object.assign(form,{directionId:directions.value[0]?.id,name:'',type:'SKILL',description:'',priority:'MEDIUM',startDate:dayjs().format('YYYY-MM-DD'),dueDate:dayjs().add(60,'day').format('YYYY-MM-DD'),weeklyBudgetMinutes:420,repositoryUrl:''});dialog.value=true}
async function save(){loading.value=true;try{if(kind.value==='goal')await api({method:'POST',url:'/goals',data:{...form,directionId:Number(form.directionId),successCriteria:[{type:'OUTCOME',description:'完成目标验收'}]}});else await api({method:'POST',url:'/projects',data:{primaryDirectionId:Number(form.directionId),name:form.name,description:form.description,startDate:form.startDate,dueDate:form.dueDate,priority:form.priority,deliverables:[{name:'项目成果'}],repositoryUrl:form.repositoryUrl}});dialog.value=false;ElMessage.success('创建成功');await load()}finally{loading.value=false}}
async function action(item:any,a:string){let body:any={reason:`用户执行${a}`,exceptionConfirmed:false};if(['completion','cancellation'].includes(a)){try{body.reason=await ElMessageBox.prompt('请填写操作原因','需要确认',{inputValidator:v=>!!v||'原因不能为空'}).then(x=>x.value)}catch{return}}await api({method:'POST',url:`/${tab.value}/${item.publicId}/${a}`,data:body});ElMessage.success('状态已更新');await load()}
</script>
<template><div><div class="page-head"><div><h2>目标决定方向，项目承载成果</h2><p>状态变更遵循生命周期规则；完成和取消操作会被审计。</p></div><el-button type="primary" @click="create(tab==='goals'?'goal':'project')">新建{{tab==='goals'?'目标':'项目'}}</el-button></div><section class="panel"><el-tabs v-model="tab"><el-tab-pane label="学习目标" name="goals"><el-table :data="goals"><el-table-column label="目标" min-width="240"><template #default="{row}"><b>{{row.name}}</b><div class="muted row-desc">{{row.description||'暂无描述'}}</div></template></el-table-column><el-table-column prop="type" label="类型" width="110"/><el-table-column label="周期" width="220"><template #default="{row}">{{row.startDate}} → {{row.dueDate}}</template></el-table-column><el-table-column prop="weeklyBudgetMinutes" label="每周预算(分)" width="130"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag effect="plain">{{row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="220"><template #default="{row}"><el-button v-if="row.status==='DRAFT'" link type="primary" @click="action(row,'activation')">激活</el-button><el-button v-if="row.status==='ACTIVE'" link @click="action(row,'pause')">暂停</el-button><el-button v-if="row.status==='PAUSED'" link @click="action(row,'resume')">恢复</el-button><el-button v-if="row.status==='ACTIVE'" link type="success" @click="action(row,'completion')">完成</el-button><el-button link type="danger" @click="action(row,'cancellation')">取消</el-button></template></el-table-column></el-table></el-tab-pane><el-tab-pane label="实践项目" name="projects"><el-table :data="projects"><el-table-column prop="name" label="项目" min-width="240"/><el-table-column prop="priority" label="优先级" width="100"/><el-table-column label="周期" width="220"><template #default="{row}">{{row.startDate}} → {{row.dueDate}}</template></el-table-column><el-table-column prop="status" label="状态" width="110"/><el-table-column label="操作" width="210"><template #default="{row}"><el-button v-if="row.status==='DRAFT'" link type="primary" @click="action(row,'activation')">激活</el-button><el-button v-if="row.status==='ACTIVE'" link @click="action(row,'pause')">暂停</el-button><el-button v-if="row.status==='PAUSED'" link @click="action(row,'resume')">恢复</el-button><el-button link type="success" @click="action(row,'completion')">完成</el-button></template></el-table-column></el-table></el-tab-pane></el-tabs></section>
<el-dialog v-model="dialog" :title="kind==='goal'?'创建学习目标':'创建实践项目'" width="620"><el-form label-position="top"><el-form-item label="名称"><el-input v-model="form.name" maxlength="120"/></el-form-item><el-form-item label="学习方向"><el-select v-model="form.directionId" class="full"><el-option v-for="d in directions" :key="d.id" :value="d.id" :label="d.name"/></el-select></el-form-item><div class="grid grid-2"><el-form-item v-if="kind==='goal'" label="目标类型"><el-select v-model="form.type" class="full"><el-option value="SKILL" label="技能"/><el-option value="EXAM" label="考试"/><el-option value="PROJECT" label="项目"/></el-select></el-form-item><el-form-item label="优先级"><el-select v-model="form.priority" class="full"><el-option value="LOW"/><el-option value="MEDIUM"/><el-option value="HIGH"/><el-option value="URGENT"/></el-select></el-form-item><el-form-item label="开始日期"><el-date-picker v-model="form.startDate" value-format="YYYY-MM-DD" class="full"/></el-form-item><el-form-item label="截止日期"><el-date-picker v-model="form.dueDate" value-format="YYYY-MM-DD" class="full"/></el-form-item></div><el-form-item v-if="kind==='goal'" label="每周预算（分钟）"><el-input-number v-model="form.weeklyBudgetMinutes" :min="10" :max="6720"/></el-form-item><el-form-item v-else label="代码仓库"><el-input v-model="form.repositoryUrl"/></el-form-item><el-form-item label="说明"><el-input v-model="form.description" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="loading" @click="save">创建</el-button></template></el-dialog></div></template>
<style scoped>.row-desc{font-size:11px;margin-top:5px}</style>
