<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, idempotencyKey } from '../api/http'
const goals=ref<any[]>([]), selectedGoal=ref(''), job=ref<any>(), detail=ref<any>(), generating=ref(false), publishing=ref(false), requirement=ref('')
const changes=computed(()=>detail.value?.changes||[]); const validations=computed(()=>detail.value?.validation||[]); const canPublish=computed(()=>detail.value?.version?.status==='READY')
onMounted(async()=>{const p=await api<any>({url:'/goals',params:{status:'ACTIVE',pageSize:100}});goals.value=p.items;selectedGoal.value=goals.value[0]?.publicId||''})
async function generate(){generating.value=true;try{job.value=await api<any>({method:'POST',url:`/goals/${selectedGoal.value}/planning-jobs`,headers:{'Idempotency-Key':idempotencyKey()},data:{type:'INITIAL',userRequirement:requirement.value}});if(job.value.planVersionId)detail.value=await api<any>({url:`/plan-versions/${job.value.planVersionId}`});ElMessage.success('Agent 已生成可审阅方案，尚未修改任何任务')}finally{generating.value=false}}
async function validate(){detail.value=await api<any>({method:'POST',url:`/plan-versions/${detail.value.version.publicId}/validation`});ElMessage.success('约束校验完成')}
async function publish(){await ElMessageBox.confirm(`将应用 ${changes.value.length} 项变更。发布后生成正式任务，是否继续？`,'高影响操作确认',{confirmButtonText:'确认发布',type:'warning'});publishing.value=true;try{const c=await api<any>({method:'POST',url:`/plan-versions/${detail.value.version.publicId}/confirmation-requests`});const result=await api<any>({method:'POST',url:`/plan-versions/${detail.value.version.publicId}/publication`,headers:{'Idempotency-Key':idempotencyKey()},data:{confirmationToken:c.token}});ElMessage.success(`计划 v${result.versionNo} 已发布，共变更 ${result.changedTaskIds.length} 个任务`);detail.value.version.status='PUBLISHED'}finally{publishing.value=false}}
async function reject(){await api({method:'POST',url:`/plan-versions/${detail.value.version.publicId}/rejection`,data:{reason:'用户拒绝当前方案'}});detail.value.version.status='REJECTED';ElMessage.info('方案已拒绝，正式计划未改变')}
function after(c:any){try{return JSON.parse(c.afterJson||'{}')}catch{return{}}}
</script>
<template><div><div class="page-head"><div><h2>Agent 负责提案，你负责决定</h2><p>生成、校验、审阅、确认、发布五步分离；未发布的方案不会改变正式任务。</p></div></div><section v-if="!detail" class="panel plan-start"><div><span class="agent-orb">AI</span><h3>生成一份容量可行的学习计划</h3><p>系统使用你的画像、目标期限和可用时间，按 85% 容量上限拆分 10–120 分钟任务。</p></div><el-form label-position="top"><el-form-item label="活动目标"><el-select v-model="selectedGoal" class="full" placeholder="请先激活一个目标"><el-option v-for="g in goals" :key="g.publicId" :value="g.publicId" :label="g.name"/></el-select></el-form-item><el-form-item label="补充要求（可选）"><el-input v-model="requirement" type="textarea" :rows="4" placeholder="例如：工作日以阅读为主，周末安排项目实践"/></el-form-item><el-button type="primary" size="large" class="full" :disabled="!selectedGoal" :loading="generating" @click="generate">生成计划提案</el-button></el-form><el-empty v-if="!goals.length" description="请先创建并激活一个目标"/></section>
<template v-else><div class="plan-meta panel"><div><span class="tag">版本 {{detail.version.versionNo}}</span><h3>{{detail.version.triggerType==='OPTIMIZATION'?'优化方案':'初始计划方案'}}</h3><p>风险等级 {{detail.version.riskLevel}} · 状态 {{detail.version.status}} · 提案哈希 {{detail.version.proposalHash?.slice(0,12)}}…</p></div><div class="toolbar"><el-button @click="validate">重新校验</el-button><el-button type="danger" plain @click="reject">拒绝</el-button><el-button type="primary" :disabled="!canPublish" :loading="publishing" @click="publish">确认并发布</el-button></div></div><div class="grid plan-grid"><section class="panel"><div class="panel-title"><div><h3>变更清单</h3><p>{{changes.length}} 项提议，逐项说明原因</p></div></div><div v-for="(c,i) in changes" :key="c.publicId" class="change"><div class="change-no">{{String(i+1).padStart(2,'0')}}</div><div><div><b>{{after(c).title}}</b> <span class="tag">{{c.action}}</span></div><p>{{c.reason}}</p><small>{{after(c).estimatedMinutes}} 分钟 · {{after(c).scheduledStart?.replace('T',' ')}}</small></div></div></section><aside class="panel"><div class="panel-title"><div><h3>约束校验</h3><p>发布前必须全部通过</p></div></div><div v-for="v in validations" :key="v.ruleCode" class="validation"><span :class="v.passed?'pass':'fail'">{{v.passed?'✓':'!'}}</span><div><b>{{v.ruleCode}}</b><small>{{v.message}}</small></div></div><div v-if="!validations.length" class="empty">点击重新校验</div></aside></div></template></div></template>
<style scoped>.plan-start{display:grid;grid-template-columns:1fr 1fr;gap:70px;padding:60px;align-items:center;max-width:1050px;margin:auto}.plan-start h3{font:400 30px 'DM Serif Display','Noto Sans SC';margin:20px 0 10px}.plan-start p{color:var(--muted);line-height:1.8}.agent-orb{display:grid;place-items:center;width:65px;height:65px;background:var(--green);color:#fff;border-radius:22px 22px 22px 6px;font:700 18px monospace}.plan-meta{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.plan-meta h3{margin:8px 0}.plan-meta p{font-size:12px;color:var(--muted);margin:0}.plan-grid{grid-template-columns:1.5fr .75fr}.change{display:grid;grid-template-columns:42px 1fr;gap:13px;border-top:1px solid var(--line);padding:16px 0}.change-no{color:#99a39b;font:18px 'DM Serif Display'}.change p{font-size:12px;margin:6px 0;color:var(--muted)}.change small{font-size:11px;color:var(--green)}.validation{display:flex;gap:10px;margin:12px 0}.validation>span{display:grid;place-items:center;width:26px;height:26px;border-radius:50%;flex:none}.validation .pass{background:var(--mint);color:var(--green)}.validation .fail{background:#f5dddd;color:var(--red)}.validation b,.validation small{display:block}.validation b{font-size:12px}.validation small{font-size:10px;color:var(--muted);margin-top:3px}@media(max-width:900px){.plan-start,.plan-grid{grid-template-columns:1fr}.plan-start{padding:25px}}</style>
