<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api/http'
import { useAuthStore } from '../stores/auth'
const auth=useAuthStore(),account=reactive({email:'',timezone:'Asia/Shanghai',version:0}),prefs=reactive<Record<string,boolean>>({TASK_DUE:true,TASK_OVERDUE:true,REPORT:true,DOCUMENT:true}),prefVersion=ref(0),loading=ref(false),notifications=ref<any[]>([])
onMounted(async()=>{const [u,p,n]=await Promise.all([api<any>({url:'/users/me'}),api<any>({url:'/notification-preferences'}),api<any>({url:'/notifications',params:{pageSize:10}})]);Object.assign(account,u);Object.assign(prefs,p.values);prefVersion.value=p.version;notifications.value=n.items})
async function save(){loading.value=true;try{const u=await api<any>({method:'PATCH',url:'/users/me',data:account});Object.assign(account,u);auth.user=u;localStorage.setItem('user',JSON.stringify(u));const p=await api<any>({method:'PUT',url:'/notification-preferences',data:{values:prefs,version:prefVersion.value}});prefVersion.value=p.version;ElMessage.success('设置已保存')}finally{loading.value=false}}
async function logoutAll(){await ElMessageBox.confirm('这会撤销所有设备上的刷新令牌，当前设备也需要重新登录。','退出所有设备',{type:'warning'});await api({method:'POST',url:'/auth/logout-all'});localStorage.clear();location.assign('/login')}
</script>
<template><div class="settings"><div class="page-head"><div><h2>账户与提醒</h2><p>时区影响任务归属日、学习时长切分和所有统计区间。</p></div><el-button type="primary" :loading="loading" @click="save">保存设置</el-button></div><div class="grid settings-grid"><section class="panel"><div class="panel-title"><div><h3>账户信息</h3><p>用户名不可修改</p></div></div><el-form label-position="top"><el-form-item label="邮箱"><el-input v-model="account.email"/></el-form-item><el-form-item label="IANA 时区"><el-input v-model="account.timezone" placeholder="Asia/Shanghai"/></el-form-item></el-form><el-divider/><div class="security"><div><b>退出所有设备</b><p>安全事件发生时撤销全部会话。</p></div><el-button type="danger" plain @click="logoutAll">全部退出</el-button></div></section><section class="panel"><div class="panel-title"><div><h3>通知偏好</h3><p>安全通知不会被关闭</p></div></div><div class="pref-row"><span>任务即将到期</span><el-switch v-model="prefs.TASK_DUE"/></div><div class="pref-row"><span>任务已经逾期</span><el-switch v-model="prefs.TASK_OVERDUE"/></div><div class="pref-row"><span>学习报告完成</span><el-switch v-model="prefs.REPORT"/></div><div class="pref-row"><span>文档处理完成</span><el-switch v-model="prefs.DOCUMENT"/></div></section></div><section class="panel recent"><div class="panel-title"><div><h3>最近通知</h3><p>相同业务事件使用去重键，避免重复提醒。</p></div></div><div v-if="!notifications.length" class="empty">暂无通知</div><div v-for="n in notifications" :key="n.publicId" class="notification"><span :class="{unread:!n.readAt}"/><div><b>{{n.title}}</b><p>{{n.content}}</p></div><small>{{n.createdAt}}</small></div></section></div></template>
<style scoped>.settings{max-width:1050px;margin:auto}.settings-grid{grid-template-columns:1fr 1fr}.pref-row,.security,.notification{display:flex;justify-content:space-between;align-items:center;border-top:1px solid var(--line);padding:15px 0}.security p,.notification p{margin:4px 0;color:var(--muted);font-size:11px}.recent{margin-top:18px}.notification{display:grid;grid-template-columns:8px 1fr 180px;gap:10px}.notification>span{width:7px;height:7px;border-radius:50%;background:#c5cbc6}.notification>span.unread{background:var(--green)}.notification small{color:var(--muted)}@media(max-width:800px){.settings-grid{grid-template-columns:1fr}}</style>
