<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import dayjs from 'dayjs'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api/http'
const date=ref(dayjs().format('YYYY-MM-DD')), tasks=ref<any[]>([]), selected=ref<any>(), session=ref<any>(), elapsed=ref(0), note=ref({title:'学习笔记',markdown:'',version:undefined as number|undefined}), timer=ref<number>()
const entity=computed(()=>selected.value?.task||{}); const running=computed(()=>Boolean(session.value)&&session.value.status==='RUNNING')
async function load(){tasks.value=await api<any[]>({url:'/tasks',params:{date:date.value}});if(selected.value){selected.value=tasks.value.find(x=>x.task.publicId===entity.value.publicId)}}
onMounted(load);onUnmounted(()=>timer.value&&clearInterval(timer.value))
async function select(row:any){selected.value=row;try{const n=await api<any>({url:`/tasks/${row.task.publicId}/note`});if(n?.note)note.value={title:n.note.title,markdown:n.currentVersion?.contentMarkdown||'',version:n.note.version}}catch{/* empty note */}}
function runClock(){timer.value=window.setInterval(()=>elapsed.value++,1000)}
async function start(){session.value=await api<any>({method:'POST',url:`/tasks/${entity.value.publicId}/start`,data:{startTimer:true}});elapsed.value=0;runClock();await load()}
async function pause(){await api({method:'POST',url:`/study-sessions/${session.value.publicId}/pause`});session.value.status='PAUSED';if(timer.value)clearInterval(timer.value)}
async function resume(){await api({method:'POST',url:`/study-sessions/${session.value.publicId}/resume`});session.value.status='RUNNING';runClock()}
async function stop(){await api({method:'POST',url:`/study-sessions/${session.value.publicId}/stop`});session.value=undefined;if(timer.value)clearInterval(timer.value);await load();ElMessage.success('学习时长已记录')}
async function saveNote(){const n=await api<any>({method:'PUT',url:`/tasks/${entity.value.publicId}/note`,data:note.value});note.value.version=n.note.version;ElMessage.success('笔记已保存并生成历史版本')}
async function complete(){const summary=await ElMessageBox.prompt('写一句完成总结','完成任务',{inputValidator:v=>!!v||'完成总结不能为空'}).then(x=>x.value).catch(()=>null);if(!summary)return;await api({method:'POST',url:`/tasks/${entity.value.publicId}/completion`,data:{summary,confirmed:true}});await load();ElMessage.success('任务已完成')}
const formatTime=computed(()=>`${String(Math.floor(elapsed.value/60)).padStart(2,'0')}:${String(elapsed.value%60).padStart(2,'0')}`)
</script>
<template><div><div class="page-head"><div><h2>今天，只完成今天</h2><p>执行状态与排期状态分别计算；暂停不会被误判为逾期。</p></div><el-date-picker v-model="date" value-format="YYYY-MM-DD" @change="load"/></div><div class="grid today-grid"><section class="panel"><div class="panel-title"><div><h3>任务队列</h3><p>{{tasks.length}} 个行动项</p></div></div><div v-if="!tasks.length" class="empty">当天没有已发布任务</div><button v-for="row in tasks" :key="row.task.publicId" class="today-task" :class="{active:entity.publicId===row.task.publicId}" @click="select(row)"><span :class="['priority',row.task.priority?.toLowerCase()]"/><div><b>{{row.task.title}}</b><small>{{row.task.estimatedMinutes}} 分钟 · {{row.scheduleStatus}}</small></div><el-tag size="small" effect="plain">{{row.task.lifecycleStatus}}</el-tag></button></section><section class="panel workspace"><div v-if="!selected" class="empty">选择一个任务进入学习工作区</div><template v-else><div class="panel-title"><div><span class="tag">{{entity.taskType}}</span><h3>{{entity.title}}</h3><p>{{entity.description}}</p></div><el-button v-if="entity.lifecycleStatus!=='COMPLETED'" type="success" plain @click="complete">标记完成</el-button></div><div class="timer-box"><span>{{formatTime}}</span><small>{{session?.status||'尚未开始计时'}}</small><div><el-button v-if="!session" type="primary" @click="start">开始专注</el-button><el-button v-else-if="running" @click="pause">暂停</el-button><el-button v-else @click="resume">继续</el-button><el-button v-if="session" type="danger" plain @click="stop">结束记录</el-button></div></div><el-tabs><el-tab-pane label="学习笔记"><el-input v-model="note.title" placeholder="笔记标题"/><el-input v-model="note.markdown" type="textarea" :rows="10" placeholder="支持 Markdown；保存时生成不可变版本" class="note-area"/><el-button type="primary" @click="saveNote">保存笔记</el-button></el-tab-pane><el-tab-pane label="任务信息"><el-descriptions :column="1" border><el-descriptions-item label="计划开始">{{entity.scheduledStart}}</el-descriptions-item><el-descriptions-item label="截止时间">{{entity.dueAt}}</el-descriptions-item><el-descriptions-item label="预计时长">{{entity.estimatedMinutes}} 分钟</el-descriptions-item><el-descriptions-item label="来源">{{entity.source}}</el-descriptions-item></el-descriptions></el-tab-pane></el-tabs></template></section></div></div></template>
<style scoped>.today-grid{grid-template-columns:.85fr 1.5fr}.today-task{width:100%;display:grid;grid-template-columns:8px 1fr auto;align-items:center;text-align:left;gap:12px;padding:16px 10px;border:0;border-top:1px solid var(--line);background:transparent}.today-task.active{background:#eef4ef}.today-task b,.today-task small{display:block}.today-task small{color:var(--muted);font-size:11px;margin-top:5px}.priority{width:7px;height:35px;border-radius:5px;background:#aeb8b0}.priority.high,.priority.urgent{background:var(--red)}.priority.medium{background:var(--gold)}.workspace{min-height:620px}.workspace h3{margin:10px 0 5px}.timer-box{text-align:center;background:#173d31;color:white;border-radius:15px;padding:24px;margin:10px 0 22px}.timer-box>span,.timer-box>small{display:block}.timer-box>span{font:42px monospace;letter-spacing:.08em}.timer-box>small{color:#aec6bb;margin:5px 0 15px}.note-area{margin:12px 0}@media(max-width:900px){.today-grid{grid-template-columns:1fr}}</style>
